name: GitHub Actions CI/CD
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker Images
        run: docker-compose build
      - name: Run Docker Compose
        run: docker-compose up -d
